import type { DailyReportPreview, ProjectConfig, ProjectStatus } from '../shared/types.js'
import type { SecretProvider } from './security.js'

function countLine(locale: 'zh-CN' | 'en-US', labelZh: string, labelEn: string, count: number): string {
  if (locale === 'zh-CN') return `- ${labelZh}：${new Intl.NumberFormat(locale).format(count)}`
  const unit = count === 1 ? 'item' : 'items'
  return `- ${labelEn}: ${new Intl.NumberFormat(locale).format(count)} ${unit}`
}

export function generateDailyReport(project: ProjectConfig, status: ProjectStatus, locale: 'zh-CN' | 'en-US'): DailyReportPreview {
  const now = new Date()
  const date = new Intl.DateTimeFormat(locale, { dateStyle: 'full', timeZone: project.dailyReport.timezone }).format(now)
  const isZh = locale === 'zh-CN'
  const actionLabels: Record<string, [string, string]> = {
    review: ['等待人工批改', 'Awaiting human review'], testing: ['等待候选测试', 'Awaiting candidate test'], rework: ['等待返工', 'Awaiting rework'],
    merge: ['等待最终合入', 'Awaiting final merge'], release: ['等待发布', 'Awaiting release'], deploy: ['等待人工部署', 'Awaiting manual deployment'],
  }
  const lines = [
    `# ${project.displayName} ${isZh ? '开发日报' : 'Development Brief'}`,
    '',
    `> ${date} · ${isZh ? '由 Factory Console 生成' : 'Generated by Factory Console'}`,
    '',
    `## ${isZh ? '当前队列' : 'Current queues'}`,
    '',
    countLine(locale, '待开发', 'To develop', status.metrics.todo),
    countLine(locale, '开发中', 'In progress', status.github.issues.filter((issue) => issue.labels.includes('status:doing')).length),
    countLine(locale, '等待人工批改', 'Awaiting human review', status.metrics.review),
    countLine(locale, '待修改', 'Rework', status.metrics.rework),
    countLine(locale, '待测试', 'Candidate testing', status.metrics.testing),
    '',
    `## ${isZh ? '人工事项' : 'Human actions'}`,
    '',
    ...(status.actions.length
      ? status.actions.map((action) => `- ${actionLabels[action.kind]?.[isZh ? 0 : 1] ?? action.kind}: ${new Intl.NumberFormat(locale).format(action.count)}${action.targetUrl ? ` (${action.targetUrl})` : ''}`)
      : [`- ${isZh ? '当前没有等待人工处理的事项。' : 'No human action is currently waiting.'}`]),
    '',
    `## ${isZh ? '阻塞与建议' : 'Blocks and suggested next step'}`,
    '',
    status.factory.summary
      ? `- ${status.factory.summary}`
      : `- ${isZh ? 'Factory 未返回下一步；请先运行 doctor 检查环境。' : 'Factory did not return a next step; run doctor to inspect the environment.'}`,
    '',
    `## ${isZh ? '昨日完成' : 'Completed yesterday'}`,
    '',
    `- ${isZh ? 'MVP 当前仅从实时开放状态推导队列；历史完成项需要 GitHub 时间窗口聚合。' : 'The MVP currently derives queues from live open state; historical completion requires GitHub time-window aggregation.'}`,
  ]
  return {
    projectId: project.id,
    generatedAt: now.toISOString(),
    markdown: lines.join('\n'),
    sent: false,
    notificationConfigured: project.notification.type === 'webhook' && Boolean(project.notification.target && project.notification.webhookSecretRef),
  }
}

export async function sendDailyReport(
  preview: DailyReportPreview,
  project: ProjectConfig,
  secrets: SecretProvider,
): Promise<DailyReportPreview> {
  if (project.notification.type !== 'webhook' || !project.notification.target) throw new Error('notification_not_configured')
  const secret = secrets.resolve(project.notification.webhookSecretRef)
  if (!secret) throw new Error('notification_secret_not_configured')
  const response = await fetch(project.notification.target, {
    method: 'POST',
    headers: { 'content-type': 'application/json', authorization: `Bearer ${secret}` },
    body: JSON.stringify({ text: preview.markdown }),
    signal: AbortSignal.timeout(15_000),
  })
  if (!response.ok) throw new Error(`notification_failed_${response.status}`)
  return { ...preview, sent: true }
}
